language: node_js
node_js:
- node
sudo: false
script: npm run test --silent && npm run build && npm run clean
deploy:
  provider: npm
  email: rthaut@gmail.com
  api_key:
    secure: Dov2dSTq+D13xkRpYNiI5eL8xRgp6Ohx9by/KgACkp7o/CkZUD0qB8uKYRilDtIFp5DbfGnP2632TISrruicQX7yDga2bsnAYQ9ts79WLFTwuj490hYoQbOUOCrTXGt0fgsOsXR8FVIdhn2EjIZI55YbE71yqBYYMfw5H05V6+dW73ZV3UpoKmF2NW5XJj83xBFljeEdasLdFExTxl0ijzjRTXBNWUgi+2Q1yjbj7220f64ltLsZnyyGpb4bZORdYfdjSDRpO23bClKmp2RctsyCWWwXWIc1chKNjRnphignQ8ABMiD2r19ccu/jM/7Te94Qxc/LvxW7o7x4ZTnCeCwz6uNOfYoX+2pMk5XFTvPSFZuVXIz3S2Fd6JQ2356zwnafC6jP/XnX6hhNA8E3CgAbf9spN/nfdqLF7N5rgKTWhxv61oQfiaRHtIBO8WWbVs4h3DaYP4LDM40tuGBEo7aCBjlyT8BuyElnaG6NRgnpqvKKUCHZfCIMZN1Hc6isaPMFky1UGv5rtYJQo2brY2g7wfLSnSYgL98kPm26q3+WQZDUjWzFEQPzxo3PQsgbcguMYLVC9SxTcfYylPHCab1U5efZsrcRSgo9WhO5vfhND6ylpxx5itcLtC/JM4ohzx/Tl8TZHjSgLeF4btGdWgseyBno19pVyaBmYEAFt+Y=
  on:
    repo: rthaut/angular-browser-i18n
  skip_cleanup: true
