language: node_js
node_js:
- node
sudo: false
script: npm run test --silent && npm run build && npm run clean
deploy:
  provider: npm
  email: rthaut@gmail.com
  api_key:
    secure: jOQYV9jy8dRu5cn8jSkz9IbEuGm580osD1Dd9ud4PSoHMOO9rbbJLbWIa8a/2CWGbLRegEJP0IOnqw6DIgFlgSVw+UJM90t+IJEg4M5rtlkuq4KkVbB9ZrTIAXpwqLTyd23JtTyJB6JXTZ4BkPziSgs33nyiQgHX5usf1sUxt9IVsUrXrbLombxpNNGsEPfbOPpRElYPK8eThmOTM8ZdHcvllV0FcLmXEPk0iyUNdkogrh0BFGPFstoWO7Ca2MgwL86pUHHK2MAWKn5+od8Ow5tmtssg/oFc/2DZZQC1x1UT1H+T71o1iQwq7T6UdcwTeETdU4jrx4yzDrp6yl0/nwIeneGIiJbk36MQ4w/2DUB1eeqlaYuqnorgOrZg9oGghMeDNo6Vu+vghYSbefgBJeQTrYiEA74oOrMkAV0u+5QX36bDz/QXX3zxhW2AT5XhI0kL1LbJO2YolFHqEF/Gm3eY+j5JAGB/saq1xD+mUOuFImBM5wTOPX1ZUWhi0C1hYcQoGRBVaOE/BkiaEBmvLpsR7WsAjAfHc1u0dHq7StwwE0xK5JRItKo74VSCPofVNV4QeGhkmBT2Ex+tPl+X+Vz1GkKremK5XZ6vKXIaxLvldn1rYFkIH0Qxd5ECbENLP5bupAaQUVefK1Zhk68cju+ysrzPl+rk4OMUHvLE0x0=
  on:
    repo: rthaut/angular-browser-i18n
  skip_cleanup: true
